# Do NOT change the config version!
config_version: 1
# Set locale for user dialog messages
language: de
# Enable debug output
debug: false
#
# eMail host options
#
# SMTP host name (e.g. mail.arcor.de) for sending eMail
smtpHostName: my.smtp.host
# userName for mail account of given smtp host
userName: 'none'
# Password for given user mail account
password: 'none'
# Senders email address
senderMailAddress: 'me@host.com'
# Receivers email address
receiverMailAddress: 'you@otherhost.com'
#
# HTTP Request options
#
# Gateway URL
gatewayURL: 'https://myGateway.smsService.de/'
# Gateway username
gatewayUser: 'User'
# Gateway password (may be delivered in raw text or (preferred) as md5 string
# (for security reasons)
gatewayPassword: 'Password'
# Name of sender of SMS. CAUTION: The length of this name +2 chars will be
# subtracted from the 160 character limit of a message.
smsSenderName: 'ServerName'
# mobile phone number of receiver
smsReceiverNumber: '012398765432'
